import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import { IsLoggedInProvider } from "@/components/login/isLoggedInContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <IsLoggedInProvider>
          <header>  
            <Header />
          </header>
        
          {children}
        </IsLoggedInProvider>
      </body>
    </html>
  );
}